# Generated by Django 4.1.1 on 2022-09-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='token',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
